import type { Metadata } from "next";
import { locales, siteUrl, type Locale } from "@/lib/i18n/config";

/**
 * Fallback social card — the brand lockup, regenerated by
 * `npm run brand:images`. Every page needs *some* og:image: without one,
 * LinkedIn, WhatsApp and Slack render a bare text row that reads as a broken
 * or untrustworthy link.
 */
export const defaultOgImage = {
  url: `${siteUrl}/og/klent-creative.png`,
  width: 1200,
  height: 630,
  alt: "KLENT CREATIVE — La Rochelle / Barcelona / Córdoba",
};

/**
 * og:locale wants a language_TERRITORY pair, not a bare language code. "fr"
 * and "en" alone are technically invalid and some scrapers drop the tag, so
 * these are spelled out rather than derived from the hreflang value.
 */
const ogLocale: Record<Locale, string> = {
  fr: "fr_FR",
  es: "es_ES",
  "es-ar": "es_AR",
  en: "en_US",
};

type SocialInput = {
  locale: Locale;
  title: string;
  description: string;
  /** Absolute URL of this page. */
  url: string;
  /** Page-specific image (article cover, project shot). Falls back to the brand card. */
  image?: string;
  publishedTime?: string;
  modifiedTime?: string;
};

/**
 * Builds the Open Graph + Twitter blocks. Centralised because Next.js does not
 * deep-merge `openGraph` across layouts: any page that declares its own
 * replaces the parent's wholesale, so a default set once in the root layout
 * would silently vanish on every page that customises the title.
 */
export function buildSocial({
  locale,
  title,
  description,
  url,
  image,
  publishedTime,
  modifiedTime,
}: SocialInput): Pick<Metadata, "openGraph" | "twitter"> {
  const images = image ? [image] : [defaultOgImage];
  const isArticle = Boolean(publishedTime);

  return {
    openGraph: {
      title,
      description,
      url,
      siteName: "Klent Creative",
      locale: ogLocale[locale],
      alternateLocale: locales.filter((l) => l !== locale).map((l) => ogLocale[l]),
      images,
      ...(isArticle
        ? { type: "article" as const, publishedTime, modifiedTime }
        : { type: "website" as const }),
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images,
    },
  };
}
