import type { Locale } from "@/lib/i18n/config";
import type { ProjectContent } from "@/lib/i18n/project-content";

const baseStudy: NonNullable<ProjectContent["caseStudy"]> = {
  year: "2026",
  location: "Barcelona / La Rochelle",
  scope: "Application mobile / Site web / UX/UI / Développement",
  status: "Projet réel / Produit lancé",
  theme: { primary: "#FFD200", secondary: "#FFFFFF", dark: "#000000", accent: "#FFD200" },
  variant: "oxploria",
  logoLines: ["OXPLORIA"],
  logo: "/projects/oxploria/logo-oxploria.svg",
  abstractCover: true,
  coverCaption: "Application mobile / Plateforme culturelle",
  conceptEyebrow: "01 / LE PRODUIT",
  conceptTitle: "Découvrir une ville par les histoires qu’elle porte.",
  conceptBody: "Oxploria révèle les monuments, les statues, les détails architecturaux et les lieux que l’on traverse sans toujours les remarquer. L’expérience privilégie les faits et le contexte : aucun avis, aucune note, aucun classement imposé.",
  identityEyebrow: "02 / SYSTÈME VISUEL",
  identityTitle: "Une identité qui donne envie d’explorer.",
  identityBody: "Le noir structure l’information, le blanc préserve la clarté et le jaune #FFD200 devient un signal de découverte. Le repère cartographique intégré au logo relie immédiatement la marque à l’exploration urbaine.",
  logoNote: "Le logotype associe le nom à un repère de carte et à une boussole : localisation, orientation et curiosité réunies dans un signe identifiable.",
  colors: [
    { name: "Noir", hex: "#000000" },
    { name: "Blanc", hex: "#FFFFFF" },
    { name: "Jaune Oxploria", hex: "#FFD200" },
  ],
  typographyTitle: "Claire sur un écran. Forte dans la ville.",
  typographyBody: "Une typographie sans serif assure la lisibilité des distances, catégories et informations pratiques. Les grands titres gardent une présence directe et contemporaine.",
  typePrimaryLabel: "Typographie display / Sans serif",
  typeDisplayLines: ["La ville", "autrement."],
  typeSecondaryLabel: "Typographie fonctionnelle / Interface",
  typeSample: "A–Z / 0–9 / DISTANCE / CATÉGORIE / HISTOIRE",
  voiceEyebrow: "03 / EXPÉRIENCE",
  voiceTitle: "Pas de bruit. Juste l’histoire.",
  voiceBody: "Oxploria ne juge pas les lieux : l’application les raconte. La voix est simple, factuelle et curieuse, pour laisser chaque histoire parler d’elle-même.",
  voiceLines: ["AUTOUR DE VOUS.", "SANS AVIS.", "JUSTE L’HISTOIRE."],
  applicationsEyebrow: "04 / APPLICATION MOBILE",
  applicationsTitle: "De la proximité à la découverte.",
  applicationsBody: "L’application permet d’explorer les lieux proches, de filtrer la ville par catégories, d’enregistrer ses découvertes, de marquer les visites et de progresser à travers sept niveaux d’explorateur donnant accès à des récompenses locales.",
  applicationOne: { caption: "Interface / Proximité", titleLines: ["NEAR", "BY"], rows: [["DISTANCE", "Places autour de vous"], ["CONTENU", "Histoire et informations"], ["ACTION", "Enregistrer / Visiter"]] },
  applicationTwo: { caption: "Navigation / Catégories", titleLines: ["EX", "PLORE"], small: "CULTURE / NATURE / LOCAL LIFE", sticker: ["OXP", "APP"] },
  applicationPhoto: { caption: "Produit / Mobile", lines: ["VOIR.", "COMPRENDRE."] },
  galleryImages: [
    { src: "/projects/oxploria/gallery-favorites.webp", alt: "Écran des lieux sauvegardés dans l’application Oxploria", caption: "Application / Favoris" },
    { src: "/projects/oxploria/gallery-home.webp", alt: "Écran d’accueil de l’application Oxploria avec les lieux à proximité", caption: "Application / Accueil" },
    { src: "/projects/oxploria/gallery-place-detail.webp", alt: "Fiche détaillée d’un lieu dans l’application Oxploria", caption: "Application / Fiche d’un lieu" },
    { src: "/projects/oxploria/gallery-map.webp", alt: "Carte d’exploration de Barcelone dans l’application Oxploria", caption: "Application / Carte" },
  ],
  digitalEyebrow: "05 / SITE INTERNET",
  digitalTitle: "Un site qui explique le produit avant le téléchargement.",
  digitalBody: "Le site présente la proposition de valeur, les principaux parcours, les villes disponibles et les engagements de confidentialité, puis conduit naturellement vers le téléchargement de l’application.",
  digitalMockup: { url: "oxploria.com", nav: "EXPLORER   VILLES   TÉLÉCHARGER", kicker: "BARCELONA / LA ROCHELLE", headline: "DÉCOUVREZ L’HISTOIRE AUTOUR DE VOUS.", cta: "VISITER LE SITE ↗" },
  digitalScreenshot: "/projects/oxploria/mockup-oxploria.svg",
  liveUrl: "https://www.oxploria.com/en",
  resultEyebrow: "06 / RÉSULTAT",
  resultHeadline: "Une application et un site réunis dans une même expérience.",
  resultBody: "Un produit digital complet, développé pour rendre l’exploration culturelle plus directe, plus calme et plus utile — de la première découverte sur le web jusqu’à la visite dans la ville.",
};

const esStudy: NonNullable<ProjectContent["caseStudy"]> = {
  ...baseStudy,
  scope: "Aplicación móvil / Sitio web / UX/UI / Desarrollo",
  status: "Proyecto real / Producto lanzado",
  coverCaption: "Aplicación móvil / Plataforma cultural",
  conceptEyebrow: "01 / EL PRODUCTO",
  conceptTitle: "Descubrir una ciudad a través de las historias que guarda.",
  conceptBody: "Oxploria revela monumentos, estatuas, detalles arquitectónicos y lugares que cruzamos sin llegar a ver. La experiencia prioriza los hechos y el contexto: sin reseñas, puntuaciones ni rankings impuestos.",
  identityEyebrow: "02 / SISTEMA VISUAL",
  identityTitle: "Una identidad que invita a explorar.",
  identityBody: "El negro estructura la información, el blanco mantiene la claridad y el amarillo #FFD200 funciona como señal de descubrimiento. El marcador del logo conecta inmediatamente la marca con la exploración urbana.",
  logoNote: "El logotipo une el nombre con un marcador de mapa y una brújula: localización, orientación y curiosidad en un signo reconocible.",
  colors: [{ name: "Negro", hex: "#000000" }, { name: "Blanco", hex: "#FFFFFF" }, { name: "Amarillo Oxploria", hex: "#FFD200" }],
  typographyTitle: "Clara en pantalla. Presente en la ciudad.",
  typographyBody: "Una sans serif asegura la lectura de distancias, categorías e información práctica. Los titulares grandes mantienen una presencia directa y contemporánea.",
  typePrimaryLabel: "Tipografía display / Sans serif",
  typeDisplayLines: ["La ciudad", "de otra forma."],
  typeSecondaryLabel: "Tipografía funcional / Interfaz",
  typeSample: "A–Z / 0–9 / DISTANCIA / CATEGORÍA / HISTORIA",
  voiceEyebrow: "03 / EXPERIENCIA",
  voiceTitle: "Sin ruido. Solo historia.",
  voiceBody: "Oxploria no juzga los lugares: los cuenta. La voz es sencilla, factual y curiosa para dejar que cada historia hable por sí misma.",
  voiceLines: ["CERCA DE TI.", "SIN RESEÑAS.", "SOLO HISTORIA."],
  applicationsEyebrow: "04 / APLICACIÓN MÓVIL",
  applicationsTitle: "De la proximidad al descubrimiento.",
  applicationsBody: "La app permite explorar lugares cercanos, filtrar la ciudad por categorías, guardar descubrimientos, marcar visitas y avanzar por siete niveles de explorador para desbloquear recompensas locales.",
  galleryImages: [
    { src: "/projects/oxploria/gallery-favorites.webp", alt: "Pantalla de lugares guardados en la aplicación Oxploria", caption: "Aplicación / Favoritos" },
    { src: "/projects/oxploria/gallery-home.webp", alt: "Pantalla de inicio de Oxploria con lugares cercanos", caption: "Aplicación / Inicio" },
    { src: "/projects/oxploria/gallery-place-detail.webp", alt: "Ficha detallada de un lugar en la aplicación Oxploria", caption: "Aplicación / Ficha de lugar" },
    { src: "/projects/oxploria/gallery-map.webp", alt: "Mapa de exploración de Barcelona en la aplicación Oxploria", caption: "Aplicación / Mapa" },
  ],
  digitalEyebrow: "05 / SITIO WEB",
  digitalTitle: "Un sitio que explica el producto antes de descargarlo.",
  digitalBody: "La web presenta la propuesta, los recorridos principales, las ciudades disponibles y los compromisos de privacidad, y conduce de forma natural a la descarga de la aplicación.",
  digitalMockup: { url: "oxploria.com", nav: "EXPLORAR   CIUDADES   DESCARGAR", kicker: "BARCELONA / LA ROCHELLE", headline: "DESCUBRE LA HISTORIA A TU ALREDEDOR.", cta: "VISITAR EL SITIO ↗" },
  resultEyebrow: "06 / RESULTADO",
  resultHeadline: "Una aplicación y un sitio dentro de una misma experiencia.",
  resultBody: "Un producto digital completo, desarrollado para hacer la exploración cultural más directa, tranquila y útil: desde el primer contacto en la web hasta la visita en la ciudad.",
};

// Argentina reuses the Spain case study, but the few second-person strings
// have to switch to voseo — "cerca de ti" / "descubre" read as foreign there.
const esArStudy: NonNullable<ProjectContent["caseStudy"]> = {
  ...esStudy,
  voiceLines: ["CERCA DE VOS.", "SIN RESEÑAS.", "SOLO HISTORIA."],
  digitalMockup: { ...esStudy.digitalMockup, headline: "DESCUBRÍ LA HISTORIA A TU ALREDEDOR." },
};

const enStudy: NonNullable<ProjectContent["caseStudy"]> = {
  ...baseStudy,
  scope: "Mobile app / Website / UX/UI / Development",
  status: "Real project / Live product",
  coverCaption: "Mobile application / Cultural platform",
  conceptEyebrow: "01 / THE PRODUCT",
  conceptTitle: "Discover a city through the stories it carries.",
  conceptBody: "Oxploria reveals monuments, statues, architectural details and places we often pass without noticing. The experience prioritises facts and context: no reviews, ratings or imposed rankings.",
  identityEyebrow: "02 / VISUAL SYSTEM",
  identityTitle: "An identity made for exploration.",
  identityBody: "Black structures information, white protects clarity and #FFD200 yellow becomes a discovery signal. The map marker within the logo immediately connects the brand to urban exploration.",
  logoNote: "The wordmark combines the name with a map marker and compass: location, orientation and curiosity in one recognisable sign.",
  colors: [{ name: "Black", hex: "#000000" }, { name: "White", hex: "#FFFFFF" }, { name: "Oxploria yellow", hex: "#FFD200" }],
  typographyTitle: "Clear on screen. Present in the city.",
  typographyBody: "A sans serif system keeps distances, categories and practical details readable, while large headlines create a direct contemporary presence.",
  typePrimaryLabel: "Display typeface / Sans serif",
  typeDisplayLines: ["See the city", "differently."],
  typeSecondaryLabel: "Functional typeface / Interface",
  typeSample: "A–Z / 0–9 / DISTANCE / CATEGORY / HISTORY",
  voiceEyebrow: "03 / EXPERIENCE",
  voiceTitle: "No noise. Just history.",
  voiceBody: "Oxploria does not judge places; it tells their stories. The voice is simple, factual and curious, letting every place speak for itself.",
  voiceLines: ["AROUND YOU.", "NO REVIEWS.", "JUST HISTORY."],
  applicationsEyebrow: "04 / MOBILE APPLICATION",
  applicationsTitle: "From proximity to discovery.",
  applicationsBody: "The app lets people explore nearby places, filter a city by category, save discoveries, mark visits and progress through seven explorer tiers to unlock rewards from local partners.",
  galleryImages: [
    { src: "/projects/oxploria/gallery-favorites.webp", alt: "Saved places screen in the Oxploria application", caption: "Application / Favourites" },
    { src: "/projects/oxploria/gallery-home.webp", alt: "Oxploria home screen showing nearby places", caption: "Application / Home" },
    { src: "/projects/oxploria/gallery-place-detail.webp", alt: "Detailed place screen in the Oxploria application", caption: "Application / Place details" },
    { src: "/projects/oxploria/gallery-map.webp", alt: "Barcelona exploration map in the Oxploria application", caption: "Application / Map" },
  ],
  digitalEyebrow: "05 / WEBSITE",
  digitalTitle: "A website that explains the product before the download.",
  digitalBody: "The website introduces the proposition, key journeys, available cities and privacy commitments, then naturally guides visitors towards downloading the application.",
  digitalMockup: { url: "oxploria.com", nav: "EXPLORE   CITIES   DOWNLOAD", kicker: "BARCELONA / LA ROCHELLE", headline: "DISCOVER THE HISTORY AROUND YOU.", cta: "VISIT THE WEBSITE ↗" },
  resultEyebrow: "06 / OUTCOME",
  resultHeadline: "One application and website, built as a single experience.",
  resultBody: "A complete digital product developed to make cultural exploration more direct, calm and useful — from first discovery on the web to the visit in the city.",
};

const shared = {
  name: ["Oxploria"],
  image: "/projects/oxploria/app-hero.webp",
  alt: "Application mobile Oxploria dédiée à la découverte culturelle",
};

export const oxploria: Record<Locale, ProjectContent> = {
  fr: {
    ...shared,
    metaTitle: "Oxploria — Application mobile et site culturel | KLENT",
    metaDescription: "Conception et développement de l’application mobile et du site Oxploria, une expérience culturelle pour découvrir l’histoire autour de soi.",
    badge: "Projet réel",
    category: "Culture / Application mobile",
    tags: ["Flutter", "Next.js", "UX/UI", "Développement de A à Z"],
    conceptNote: "Projet réel : conception UX/UI, développement de l’application mobile et création du site internet.",
    intro: "Oxploria transforme la ville en terrain d’exploration culturelle : lieux proches, histoires documentées, catégories, favoris, visites et récompenses, réunis dans une application et son site.",
    briefTitle: "Le défi", brief: "Créer une expérience capable de donner envie de lever les yeux, comprendre les lieux rencontrés et explorer sans la pression des notes ou des classements.",
    approachTitle: "L’approche", approach: "Une application Flutter centrée sur la proximité et une plateforme web Next.js pensée pour expliquer le produit, installer la confiance et conduire au téléchargement.",
    resultTitle: "Le résultat", result: "Un écosystème cohérent, disponible en français, espagnol et anglais, conçu autour de Barcelone et La Rochelle puis prévu pour accueillir de nouvelles villes.",
    caseStudy: baseStudy,
  },
  es: {
    ...shared,
    metaTitle: "Oxploria — Aplicación móvil y sitio cultural | KLENT",
    metaDescription: "Diseño y desarrollo de la aplicación móvil y el sitio de Oxploria, una experiencia cultural para descubrir la historia cercana.",
    badge: "Proyecto real", category: "Cultura / Aplicación móvil", tags: ["Flutter", "Next.js", "UX/UI", "Desarrollo de la A a la Z"],
    conceptNote: "Proyecto real: diseño UX/UI, desarrollo de la aplicación móvil y creación del sitio web.",
    intro: "Oxploria convierte la ciudad en un territorio de exploración cultural: lugares cercanos, historias documentadas, categorías, favoritos, visitas y recompensas en una app y su sitio.",
    briefTitle: "El reto", brief: "Crear una experiencia que invite a mirar alrededor, entender los lugares y explorar sin la presión de las reseñas ni los rankings.",
    approachTitle: "El enfoque", approach: "Una aplicación Flutter centrada en la proximidad y un sitio Next.js pensado para explicar el producto, generar confianza y llevar a la descarga.",
    resultTitle: "El resultado", result: "Un ecosistema coherente en francés, español e inglés, creado para Barcelona y La Rochelle y preparado para incorporar nuevas ciudades.",
    caseStudy: esStudy,
  },
  "es-ar": {
    ...shared,
    metaTitle: "Oxploria — Aplicación móvil y sitio cultural | KLENT",
    metaDescription: "Diseño y desarrollo de la aplicación móvil y el sitio de Oxploria, una experiencia cultural para descubrir la historia cercana.",
    badge: "Proyecto real", category: "Cultura / Aplicación móvil", tags: ["Flutter", "Next.js", "UX/UI", "Desarrollo de la A a la Z"],
    conceptNote: "Proyecto real: diseño UX/UI, desarrollo de la aplicación móvil y creación del sitio web.",
    intro: "Oxploria convierte la ciudad en un territorio de exploración cultural: lugares cercanos, historias documentadas, categorías, favoritos, visitas y recompensas en una app y su sitio.",
    briefTitle: "El desafío", brief: "Crear una experiencia que invite a levantar la mirada, entender los lugares y explorar sin la presión de reseñas o rankings.",
    approachTitle: "El enfoque", approach: "Una aplicación Flutter centrada en la proximidad y un sitio Next.js pensado para explicar el producto, generar confianza y llevar a la descarga.",
    resultTitle: "El resultado", result: "Un ecosistema coherente en francés, español e inglés, creado para Barcelona y La Rochelle y preparado para sumar nuevas ciudades.",
    caseStudy: esArStudy,
  },
  en: {
    ...shared,
    metaTitle: "Oxploria — Cultural Mobile App and Website | KLENT",
    metaDescription: "Design and development of the Oxploria mobile app and website, a cultural experience for discovering the history around you.",
    badge: "Real project", category: "Culture / Mobile application", tags: ["Flutter", "Next.js", "UX/UI", "Built end-to-end"],
    conceptNote: "Real project: UX/UI design, mobile application development and website creation.",
    intro: "Oxploria turns the city into a space for cultural exploration: nearby places, documented stories, categories, favourites, visits and rewards across an application and its website.",
    briefTitle: "The challenge", brief: "Create an experience that encourages people to look around, understand places and explore without the pressure of reviews or rankings.",
    approachTitle: "The approach", approach: "A proximity-led Flutter application and a Next.js website designed to explain the product, build trust and lead naturally to the download.",
    resultTitle: "The result", result: "A coherent ecosystem in French, Spanish and English, built around Barcelona and La Rochelle and ready to welcome new cities.",
    caseStudy: enStudy,
  },
};
